# Generated by Django 4.2.9 on 2024-01-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('offender', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('message_url', models.URLField()),
                ('context', models.TextField()),
                ('ai_comment', models.TextField(default='N/A')),
                ('ai_tags', models.JSONField(default=list)),
            ],
        ),
    ]
