# Generated by Django 4.2.9 on 2024-01-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Unreviewed', 'Unrev'), ('Further Action Required', 'Bad'), ('Resolved', 'Good')], max_length=30)),
                ('description', models.TextField(default='No description provided')),
                ('platform', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Reddit', 'Reddit'), ('Youtube', 'Youtube'), ('Discord', 'Discord'), ('Twitch', 'Twitch'), ('Other', 'Other')], max_length=20)),
                ('offender', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('context', models.JSONField()),
            ],
        ),
    ]
