# Generated by Django 4.2.9 on 2024-01-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_alter_case_platform_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ai_comment',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='case',
            name='ai_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='case',
            name='context',
            field=models.TextField(),
        ),
    ]
