# Generated by Django 4.2.9 on 2024-01-07 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_case_ai_comment_case_ai_tags_alter_case_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='description',
        ),
    ]
