# Generated by Django 4.2.9 on 2024-01-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_remove_case_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='message_url',
            field=models.URLField(default='url'),
            preserve_default=False,
        ),
    ]
